name: WakaTime Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          API_BASE_URL: https://wakatime.com/api
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: last_30_days
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_TITLE: true
          CODE_LANG: java
